### ISSUE TITLE
Strange files after install

### ISSUE THREAD

**Issue by kloczek** [neilb/Graph#10]
My build process warns me about some unexpected files: installed by Graph module
```
   /usr/share/perl5/vendor_perl/Heap071/Elem.pm
   /usr/share/perl5/vendor_perl/Heap071/Fibonacci.pm
   /usr/share/perl5/vendor_perl/auto/Heap071/Elem/autosplit.ix
   /usr/share/perl5/vendor_perl/auto/Heap071/Fibonacci/autosplit.ix
```
I'm not sure for what those files are and are they really should be installed so better is to ask :P
always some .ix files should be installed when some DSO module is produced but in case of this module there is no such things.

**Comment by mohawk2** [comment]
The autosplit is more or less a legacy thing these days, and it's safe to ignore. The Heap071::* modules are deliberate, and appear to be forks out of the Heap distribution which is now at version 0.80. Regardless, there isn't an immediate problem here so I will close this for now. Please re-open if I have missed anything!
