### ISSUE TITLE
This repo has last commit 2014, but CPAN latest is from Oct 2015?

### ISSUE THREAD

**Issue by mohawk2** [neilb/Graph#11]
There's an RT issue also mentioning metadata; is this repo the authoritative source? Should GH issues be the bugtracker?

**Comment by neilb** [comment]
Good question on being the official repo. I got co-maint and was prep'ing a release, and then Jarkko did a release, but it referred to my repo, but my repo doesn't have Jarkko's latest release...

If you're interested in taking this over, you should talk to Jarkko and start from his latest release.

**Comment by mohawk2** [comment]
I did email both of you asking if help was required. Probably the starting point would be to identify the correct repo with the actual up to date info :-)

**Comment by mohawk2** [comment]
I seem to have now volunteered myself into taking care of this! :-D
